### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by mir1998** [m-jahn/SysbioTreemaps#22]
the error is: configure: error: gdal-config not found or not executable.
I cant install the sf dependecy as well as the gdal
many thanks

**Comment by m-jahn** [comment]
This is not an issue of the WeightedTreemaps package but simply of the dependencies that need to be installed. The `sf` package requires several dependencies as you can find on the CRAN info page: https://cran.r-project.org/web/packages/sf/index.html

These are GEOS, GDAL, and PROJ that all work with spatial data.

On Linux like systems, you install those using something like:

```
sudo apt install libgdal-dev libgeos-dev libproj-dev
```

You can look up the exact names in the guides to install package sf.

**Comment by mir1998** [comment]
thanks for your reply
I installed the dependencies and now i get this: do you have any idea what
i should do?

make: *** [voronoiDiagram.o] Error 1ERROR: compilation failed for
package ‘WeightedTreemaps’* removing
‘/home/labs/amit/miriame/R/x86_64-pc-linux-gnu-library/4.0/WeightedTreemaps’Warning
message:In i.p(...) :  installation of package
‘/tmp/RtmpOv24FX/file5b80149c4453/WeightedTreemaps_0.1.1.tar.gz’ had
non-zero exit status

**Comment by m-jahn** [comment]
The error message is unfortunately not very informative. The compilation of the C++ core function failed, apparently.

What system are you running? OS, version, R  version, Rstudio?

Can you see the output from compilation of the C++ function? Can you post it here?
You need to have a compiler installed, e.g. `gcc` that is preinstalled on most Linux systems.

As you can see from the GitHub actions output, the package should build fine on standard installations of Windows, MacOS and Linux. However I know that some configurations can make problems. Is it an alternative for you to use the Shiny app instead?
https://m-jahn.shinyapps.io/ShinyTreemaps/

**Comment by m-jahn** [comment]
@mir1998 Is your issue resolved?
In that case you can close the issue.

**Comment by mir1998** [comment]
Unfortunately not:(
But I asked the IT people in my university to help me since I’m working on a cluster
So I’ll close it 
Many thanks for your help 
Miriam
