### ISSUE TITLE
Saving the treemap output

### ISSUE THREAD

**Issue by unarsezer** [m-jahn/SysbioTreemaps#27]
Hi,

data(mtcars)
mtcars$car_name = gsub(" ", "\n", row.names(mtcars))

tm <- voronoiTreemap(
  data = mtcars,
  levels = c("gear", "car_name"),
  cell_size = "wt",
  shape = "circle",
  seed = 123
)

drawTreemap(tm, label_size = 3, label_color = "#34363b", width = 0.9, height = 0.9, legend = F)

After all these codes, I want to export the output as a PNG file with high resolution. I have seen that your shiny app has such a function. I mean we can save the plot as PNG. How can I do this in R Studio?

**Comment by m-jahn** [comment]
Hi @unarsezer,
saving a graphic in R is easy. Everything happens via graphic devices. If you plot something, R opens a graphic device (such as X11) automatically and shows you the plot. If you want to save a plot to hard drive, open a `png()` device:

```
png("my_treemap.png", width = 600, height = 600)
drawTreemap(tm, label_size = 3, label_color = "#34363b", width = 0.9, height = 0.9, legend = F)
dev.off()
```

Don't forget to close the device. Everthing you want to export must be between the opening and closing function (`dev.off()`) of the device.

**Comment by unarsezer** [comment]
Thank you very much!
