### ISSUE TITLE
sorting and/or labeling of cells wrong for certain labels

### ISSUE THREAD

**Issue by m-jahn** [m-jahn/SysbioTreemaps#29]
- when supplying a vector with categories as last level, the result is not identical if labels or capitalized or lower case
- specifically, group labels / cell sizes were wrong for a mix of capitalized pathway names
- changing case with `tolower()` fixed the problem, but it's unclear why it should make a difference

**Comment by olgabaranov** [comment]
Can confirm the bug. ~~Additionally, sorting the data frame by the column which is used for the labels seems to fix the issue~~ applying `tolower` or `toupper` fixes it, even though my labels were lowercase to begin with...

**Comment by m-jahn** [comment]
I need to investigate this, did not have time until now. Thanks for confirming.

**Comment by m-jahn** [comment]
I've investigating, it turned out that the error was caused by base R sorting through `table` as compared to sorting by `dplyr`s `arrange`. When do capital letters follow in succession, they treat the order differently. Compare:
```
RNA degradation
RNA polymerase
Ribosome
Unknown
```

to 

```
Ribosome
RNA degradation
RNA polymerase
Unknown 
```

Of of them gives priority to the capital writing and the other to the alphabetical order of the second letter.
