### ISSUE TITLE
Legend Argument

### ISSUE THREAD

**Issue by msgoussi** [m-jahn/SysbioTreemaps#30]
Legend in drawTreemap is either TRUE (shows in the right) or FALSE (does not show at all).

Is it possible that legend should take one of the c("none", "top", "right", "bottom", "left") options?

**Comment by m-jahn** [comment]
Totally possible, will try to add this when time. Contributions welcome!

**Comment by m-jahn** [comment]
The linked commit will solve this issue. If you check out the `dev` branch, you can already test drawing legends on all sides of the plot, and with a size argument that also controls the width/height, depending on the position.
Can't merge this with `main` branch currently, due to a missing CRAN package that fails automatic testing.

**Comment by msgoussi** [comment]
Hi... 
How to get the dev branch, Please advise.

**Comment by m-jahn** [comment]
You can use the `remotes` or `devtools` package with function `install_github`. It has arguments for installing a specified branch.
https://www.rdocumentation.org/packages/remotes/versions/2.4.2.1/topics/install_github

**Comment by msgoussi** [comment]
devtools::install_github("m-jahn/WeightedTreemaps", ref = "69705fa")

**Comment by msgoussi** [comment]
Thanks.
I think there is a problem in legend_position, right it gives the legend on the left.

**Comment by msgoussi** [comment]
my humble suggestion no need for two argument to control the legend, legend should take one of the c("none", "top", "right", "bottom", "left") instead of legend = TRUE/FALSE, then legend_position = c("top", "right", "bottom", "left").

**Comment by m-jahn** [comment]
I agree with you, but it's not always that simple: I want so ensure backwards compatibility, so taking an argument away will crash all code working with earlier versions of the package. Argument changes can be done for the next major release (CRAN?).

**Comment by msgoussi** [comment]
Hi...
I think there is a still problem in the legend position

# load example data
data(mtcars)
mtcars$car_name = gsub(" ", "\n", row.names(mtcars))
# generate treemap; set seed to obtain same pattern every time
tm <- voronoiTreemap(
  data = mtcars,
  levels = c("gear", "car_name"),
  cell_size = "wt",
  shape = "rounded_rect",
  seed = 123
)
drawTreemap(tm, label_size = 2.5, label_color = "white", legend = TRUE, legend_position = "left")

Although it is left, it shows in the right.

**Comment by m-jahn** [comment]
Haha true, left and right seems to be swapped.

**Comment by m-jahn** [comment]
Closed with commit 614e114.
