### ISSUE TITLE
Matching labels to polygon positions from a SVG Voronoi plot, generated using VoronoiTreemap() and drawTreemap() functions

### ISSUE THREAD

**Issue by mnikoli** [m-jahn/SysbioTreemaps#50]
Hi Michael, 

I've generated a (spherical) Voronoi plot using VoronoiTreemap() and drawTreemap() functions and exported it as SVG file using Cairo device and this all worked well. 
I've integrated the SVG plot to an HTML file and now I am trying to create links using labels in the plot. The problem is that each label object from the Voronoi plot is encoded as a 'glyph' structure in the SVG, and I'm looking for a way to match glyphs to my labels. Any suggestions on how this can be done?

I am able to extract polygon coordinates from my tm structure, generated using the VoronoiTreemap() along with other info, e.g.: 

$LEVEL2_ZRO2
$LEVEL2_ZRO2$name
[1] "ZRO2"

$LEVEL2_ZRO2$poly
POLYGON ((839.9788 968.31, 845.5213 986.9444, 851.0202 1005.592, 856.6495 1024.839, 862.5741 1045.244, 866.2366 1057.918, 874.3916 1059.377, 895.2085 1063.193, 915.4297 1067.043, 935.6229 1071.038, 956.3554 1075.288, 958.9713 1075.834, 968.0178 1064.94, 981.4547 1048.782, 994.1343 1033.566, 1006.434 1018.841, 1018.753 1004.132, 1031.487 988.9623, 1045.016 972.8807, 1055.553 960.3732, 1051.807 948.0169, 1045.765 927.7595, 1039.842 907.4672, 1034 887.0308, 1032.317 886.7407, 1010.174 882.9073, 989.778 879.339, 970.6004 875.9398, 952.0532 872.6031, 933.5151 869.2164, 914.3648 865.667, 894.0143 861.8483, 875.6358 858.3681, 864.8025 871.215, 851.2475 887.0989, 837.5845 902.8899, 824.6917 917.603, 828.0764 928.7611, 834.2189 949.1015, 839.9788 968.31))

...
$LEVEL2_ZRO2$site
[1] 936.1922 960.0911

$LEVEL2_ZRO2$weight
[1] 66.15718

$LEVEL2_ZRO2$area
[1] 34825.87

$LEVEL2_ZRO2$target
[1] 0.01652893

$LEVEL2_ZRO2$count
[1] 32

$LEVEL2_ZRO2$level
[1] 2

$LEVEL2_ZRO2$custom_color
[1] 20
...

but none of the coordinates doesn't seem to match those from my SVG file. Also, here's an example of how glyph0 looks like: 

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="960pt" height="960pt" viewBox="0 0 960 960" version="1.1">
<defs>
<g>
<symbol overflow="visible" id="glyph0-0">
<path style="stroke:none;" d="M 0.34375 0 L 0.34375 -7.5625 L 6.34375 -7.5625 L 6.34375 0 Z M 5.390625 -0.953125 L 5.390625 -6.625 L 1.28125 -6.625 L 1.28125 -0.953125 Z M 5.390625 -0.953125 "/>
</symbol>
 
<symbol overflow="visible" id="glyph0-1">
<path style="stroke:none;" d="M 0.234375 -0.84375 L 4.875 -6.65625 L 0.578125 -6.65625 L 0.578125 -7.5625 L 6.203125 -7.5625 L 6.203125 -6.6875 L 1.53125 -0.90625 L 6.203125 -0.90625 L 6.203125 0 L 0.234375 0 Z M 3.390625 -7.5625 Z M 3.390625 -7.5625 "/>
</symbol>
<symbol overflow="visible" id="glyph0-2">
<path style="stroke:none;" d="M 4.328125 -4.09375 C 4.804688 -4.09375 5.179688 -4.1875 5.453125 -4.375 C 5.734375 -4.570312 5.875 -4.921875 5.875 -5.421875 C 5.875 -5.960938 5.679688 -6.332031 5.296875 -6.53125 C 5.085938 -6.632812 4.804688 -6.6875 4.453125 -6.6875 L 1.953125 -6.6875 L 1.953125 -4.09375 Z M 0.921875 -7.5625 L 4.421875 -7.5625 C 5.003906 -7.5625 5.484375 -7.476562 5.859375 -7.3125 C 6.566406 -6.988281 6.921875 -6.394531 6.921875 -5.53125 C 6.921875 -5.070312 6.828125 -4.695312 6.640625 -4.40625 C 6.453125 -4.125 6.191406 -3.894531 5.859375 -3.71875 C 6.148438 -3.59375 6.367188 -3.429688 6.515625 -3.234375 C 6.671875 -3.046875 6.753906 -2.734375 6.765625 -2.296875 L 6.8125 -1.28125 C 6.820312 -0.988281 6.84375 -0.773438 6.875 -0.640625 C 6.9375 -0.390625 7.046875 -0.234375 7.203125 -0.171875 L 7.203125 0 L 5.953125 0 C 5.921875 -0.0625 5.894531 -0.144531 5.875 -0.25 C 5.851562 -0.351562 5.832031 -0.550781 5.8125 -0.84375 L 5.75 -2.109375 C 5.726562 -2.609375 5.546875 -2.941406 5.203125 -3.109375 C 5.003906 -3.203125 4.695312 -3.25 4.28125 -3.25 L 1.953125 -3.25 L 1.953125 0 L 0.921875 0 Z M 0.921875 -7.5625 "/>
</symbol>
<symbol overflow="visible" id="glyph0-3">
<path style="stroke:none;" d="M 1.015625 -5.21875 L 1.015625 -5.9375 C 1.679688 -6 2.144531 -6.101562 2.40625 -6.25 C 2.675781 -6.40625 2.875 -6.769531 3 -7.34375 L 3.734375 -7.34375 L 3.734375 0 L 2.75 0 L 2.75 -5.21875 Z M 1.015625 -5.21875 "/>
</symbol>

... 

<g style="fill:rgb(20%,20%,20%);fill-opacity:1;">
<use xlink:href="#glyph0-1" x="698.308594" y="794.941406"/>
<use xlink:href="#glyph0-2" x="704.74718" y="794.941406"/>
<use xlink:href="#glyph0-2" x="712.359226" y="794.941406"/>
<use xlink:href="#glyph0-3" x="719.971272" y="794.941406"/>
</g>
 
...

Any help would be greatly appreciated, thanks.
Miloš

**Comment by mnikoli** [comment]
I've added a text file containing glyph0 example as it's not visible from my previous post
[glyph0_example_from_svg.txt](https://github.com/user-attachments/files/17409730/glyph0_example_from_svg.txt)

**Comment by m-jahn** [comment]
Dear Milos, thanks for your interest in this package. To be honest I'm not really sure to how to handle this but I got some ideas. Depending on how much manual work you want to invest I can think of:

- open your SVG in Inkscape before exporting to HTML, and edit labels manually by adding links ([tutorial](https://proseandconst.xyz/blog/underlined-link-inkscape/))
- use a different device for export from R, not SVG or cairo PDF. There are other graphic devices that have better of text objects, and might not cut text objects into single glyphs (I think this is part of the problem, right?)

Currently there is no method to add links to text labels during creation of the treemap, so I fear you have to do this as an extra post-processing step. The coordinates of all geometrical objects are relative to a canvas of -2000 to 2000 for X and Y axes. This excludes plot margins, so these are not figure coordinates.

**Comment by mnikoli** [comment]
Thanks for the quick reply, I will look into the proposed solutions.

**Comment by m-jahn** [comment]
Any success finding a solution for your problem?

**Comment by mnikoli** [comment]
Hi Michael,
no I did not. I tried combining label information extracted from a PDF plot
version using Python and comparing it to the glyph info from an SVG file,
but the matching did not work as expected, many labels were wrongly
matched. The manual correction is not an option as there are more than a
hundred labels, and I still should try out other plotting devices.

**Comment by m-jahn** [comment]
Sorry to hear!
I hope you don't mind if I don't address this problem. I feel that replacing cell labels with hyperlinks is a bit out of scope for this package. I will close this issue with a `wontfix` label, but please feel free to add your solution if you find one.

**Comment by mnikoli** [comment]
No, please go ahead and thanks a lot for your help!
