### ISSUE TITLE
label font size control

### ISSUE THREAD

**Issue by abasseville** [m-jahn/SysbioTreemaps#55]
Hi, first, thank you for this very usefull package.
I have nevertheless a small issue related to the fontsize of the label.
I saw it was controled by label_size, but I noticed it was also related to  the number of characters in the label, the shorter labels being much larger than the longer ones. Since I work with biological pathway names, I have big differences in character length, which makes the longest names unreadable, no matter what I try (even by a numeric vector of length(label_level) which specifies the relative size of the labels for each level individually).
Would it be possible to have an option to request the same font size for all,  regardless of the number of characters in the labels?
See the example of my problem below:

```
data(mtcars)
mtcars$car_name = paste0(row.names(mtcars)," ", row.names(mtcars))
mtcars$car_name[1:5] = row.names(mtcars)[1:5] 
mtcars$car_name[5:10] = 1:5
mtcars$car_name = gsub(" ", "\n", mtcars$car_name)

tm <- voronoiTreemap(
  data = mtcars,
  levels = c("gear", "car_name"),
  cell_size = "wt",
  shape = "rounded_rect",
  seed = 123
)

drawTreemap(tm, 
            title="",
            color_type = "both", #"categorical", "cell_size", "both", or "custom_color"
            color_palette = rainbow(length(unique(mtcars$gear))),
            label_level=2, label_size = 2, border_size = 3,
            border_color = "white", label_color = "white",
            legend = F, width = 0.9)
drawTreemap(tm, 
            title="",
            color_type = "both", #"categorical", "cell_size", "both", or "custom_color"
            color_palette = rainbow(length(unique(mtcars$gear))),
            label_level=2, label_size = rep(1,nrow(mtcars)), border_size = 3,
            border_color = "white", label_color = "white",
            legend = F, width = 0.9)
drawTreemap(tm, 
            title="",
            color_type = "both", #"categorical", "cell_size", "both", or "custom_color"
            color_palette = rainbow(length(unique(mtcars$gear))),
            label_level=2, label_size = rep(1,length(unique(mtcars$gear) )), border_size = 3,
            border_color = "white", label_color = "white",
            legend = F, width = 0.9)
```

Best

**Comment by m-jahn** [comment]
Dear Agnes, yes that's reasonable request.
Label size is dynamically scaled, per level, depending on the available size of the cell and the label's width, calculated from characters. I could add a new parameter `label_scaling = TRUE/FALSE` which controls if labels are scaled based on their width. I don't know when I will implement this, can take some days.

In the mean time, I recommend you to:

1. trim long labels to a max of N characters like `df$pathway = substr(df$pathway, 1, 25)`
2. if pathways consist of multiple words, insert line breaks: `df$pathway = gsub(df$pathway, " ", "\n")`
3. pad short labels with extra spaces no make them more equa to long ones: `df$pathway = paste0("   ", df$pathway, "   ")`

**Comment by abasseville** [comment]
Hi Michael,
Thank you for your answer!
Indeed, adding extra spaces is a very good idea, I hadn't thought of it, and it reduced the difference in text size.

![image](https://github.com/user-attachments/assets/ee133832-81fd-4809-a9de-30c7195464a5)

**Comment by m-jahn** [comment]
OK option has been added, currently on dev branch. Will be merge with main in next release.
Basically you can turn on and off label adjustment with a new parameter:

```
data(mtcars)
mtcars$car_name = gsub(" ", "\n", row.names(mtcars))

tm <- voronoiTreemap(
  data = mtcars,
  levels = c("gear", "car_name"),
  cell_size = "wt",
  shape = "rounded_rect",
  seed = 123
)

drawTreemap(
  tm, color_type = "both",
  label_size = 3,
  label_autoscale = TRUE,
  layout = c(1, 2),
  position = c(1, 1)
)

drawTreemap(
  tm, color_type = "both",
  label_size = 3,
  label_autoscale = FALSE,
  layout = c(1, 2),
  position = c(1, 2),
  add = TRUE
)
```
![figure_labels](https://github.com/user-attachments/assets/c8ba1ea6-e199-44f2-8e41-27aca2fdfdf9)
