### ISSUE TITLE
a docker image for SysbioTreemaps will be perfect!

### ISSUE THREAD

**Issue by ChengYunazhi** [m-jahn/SysbioTreemaps#7]
Would you provide a docker image for SysbioTreemaps in feature？For biologist not familiar with bioinformatic skills，docker images will save them.

Thanks!

Yuanzhi

**Comment by m-jahn** [comment]
Hi, I haven't considered that yet but will think about it. I don't know much about Docker so this would be some time investment, but maybe worth it.

**Comment by m-jahn** [comment]
As an alternative to docker, I'm planning to make a web app for SysbioTreemaps using R shiny. This could happen in the near future and would allow everybody to plot treemaps without installing the package.

**Comment by m-jahn** [comment]
The package does not need installation of the external CGAL library anymore. Only oure R packages, see pull request #12 and discussion in #9.
