### ISSUE TITLE
install error on ubuntu

### ISSUE THREAD

**Issue by ChengYunazhi** [m-jahn/SysbioTreemaps#8]
voronoiDiagram.cpp: In function ‘SEXPREC* cropped_voronoi(Rcpp::NumericMatrix)’:
voronoiDiagram.cpp:102:10: error: ‘site’ does not name a type
     auto site = Apollonius_graph::Site_2(Point_2(sites(i, 0), sites(i, 1)), sites(i, 2));
          ^
voronoiDiagram.cpp:103:10: error: ‘handle’ does not name a type
     auto handle = ag.insert(site);
          ^
voronoiDiagram.cpp:104:23: error: ‘handle’ was not declared in this scope
     handles.push_back(handle);
                       ^
voronoiDiagram.cpp:104:23: note: suggested alternative:
In file included from /usr/include/CGAL/Unique_hash_map.h:31:0,
                 from /usr/include/CGAL/Triangulation_data_structure_2.h:34,
                 from /usr/include/CGAL/Triangulation_2.h:38,
                 from /usr/include/CGAL/Delaunay_triangulation_2.h:28,
                 from voronoiDiagram.cpp:17:
/usr/include/CGAL/Handle_hash_function.h:37:20: note:   ‘CGAL::internal::handle’
   namespace handle {
                    ^
voronoiDiagram.cpp:123:44: error: range-based ‘for’ loops are not allowed in C++98 mode
   for (Apollonius_graph::Vertex_handle h : handles)
                                            ^
voronoiDiagram.cpp:140:16: error: ISO C++ forbids declaration of ‘s’ with no type [-fpermissive]
     for (auto &s : vor.m_cropped_vd)
                ^
voronoiDiagram.cpp:140:20: error: range-based ‘for’ loops are not allowed in C++98 mode
     for (auto &s : vor.m_cropped_vd)
                    ^
voronoiDiagram.cpp:142:22: error: request for member ‘source’ in ‘s’, which is of non-class type ‘int’
       xs.push_back(s.source().x());
                      ^
voronoiDiagram.cpp:143:22: error: request for member ‘source’ in ‘s’, which is of non-class type ‘int’
       ys.push_back(s.source().y());
                      ^
voronoiDiagram.cpp:144:22: error: request for member ‘target’ in ‘s’, which is of non-class type ‘int’
       xs.push_back(s.target().x());
                      ^
voronoiDiagram.cpp:145:22: error: request for member ‘target’ in ‘s’, which is of non-class type ‘int’
       ys.push_back(s.target().y());
                      ^
voronoiDiagram.cpp:163:11: error: ISO C++ forbids declaration of ‘vertex’ with no type [-fpermissive]
     auto &vertex = h->site().point();
           ^
voronoiDiagram.cpp:163:36: error: invalid initialization of reference of type ‘int&’ from expression of type ‘const Point_2 {aka const CGAL::Point_2<CGAL::Epick>}’
     auto &vertex = h->site().point();
                                    ^
voronoiDiagram.cpp:164:41: error: request for member ‘x’ in ‘vertex’, which is of non-class type ‘int’
     NumericVector x_delta = xs - vertex.x();
                                         ^
voronoiDiagram.cpp:165:41: error: request for member ‘y’ in ‘vertex’, which is of non-class type ‘int’
     NumericVector y_delta = ys - vertex.y();
                                         ^
voronoiDiagram.cpp:210:54: error: request for member ‘x’ in ‘vertex’, which is of non-class type ‘int’
       Named("vertex") = NumericVector::create(vertex.x(), vertex.y()),
                                                      ^
voronoiDiagram.cpp:210:66: error: request for member ‘y’ in ‘vertex’, which is of non-class type ‘int’
       Named("vertex") = NumericVector::create(vertex.x(), vertex.y()),
                                                                  ^
make: *** [voronoiDiagram.o] Error 1
ERROR: compilation failed for package ‘SysbioTreemaps’
* removing ‘/home/yuanzhi/R/x86_64-pc-linux-gnu-library/3.5/SysbioTreemaps’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/Rtmpdzpw2n/fileefe491f632c/SysbioTreemaps_0.1.0.tar.gz’ had non-zero exit status

**Comment by m-jahn** [comment]
Please don't just paste an error log. I see that your installation is not working, but what have you tried? What OS are you using, what versions for R, Rcpp, CGAL?

**Comment by m-jahn** [comment]
Issue is closed because of lacking follow-up from opener.
